// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"github.com/paulmach/orb"
)

const TableNameZone = "zones"

// Zone mapped from table <zones>
type Zone struct {
	ID     string       `gorm:"column:id;type:text;primaryKey" json:"id"`
	Name   string       `gorm:"column:name;type:text;not null" json:"name"`
	Type   string       `gorm:"column:type;type:text;not null" json:"type"`
	State  *string      `gorm:"column:state;type:text;default:XX" json:"state"`
	Border orb.Geometry `gorm:"column:border;type:geometry(Geometry,4326);not null" json:"border"`
	Center orb.Point    `gorm:"column:center;type:geometry(Point,4326);not null" json:"center"`
}

// TableName Zone's table name
func (*Zone) TableName() string {
	return TableNameZone
}
